name = "Hotkeys"
description = "Hotkeys to create items"
author = "modding"
version = "0.3"
forumthread = ""
api_version = 6
priority = 1
dont_starve_compatible = true
reign_of_giants_compatible = true
shipwrecked_compatible = true
